#!/usr/bin/env python3
"""
Turn the team's seed dataset into SQL for the REAL backend schema.

    python3 docs/seed/build_backend_seed.py > docs/seed/seed_backend.sql
    psql -U <user> -d budget_app -f docs/seed/seed_backend.sql

WHY THIS EXISTS
---------------
`docs/seed/products.json` is Member 9's dataset: 49 distinct products, 257
listings, 10 Durban stores, collected in September 2026. It used to be bundled
into the frontend and filtered in the browser. It is not app data any more —
GET /search reads the backend's own `products` / `product_offers` tables — so
this script loads the same dataset into those tables instead.

Without it there is nothing in the database for /search to return, and the
Search and Compare screens cannot be demonstrated at all.

HOW THE DATASET MAPS ONTO sql/schema.sql
----------------------------------------
    store_name, suburb, lat/lng, online_only -> stores
    name, brand, category, colour, size      -> products      (deduplicated)
    price, shipping_fee, in_stock            -> product_offers (one per listing)

Two honest notes, both visible in the generated SQL:

  * `products.is_essential` is not in the source dataset. It is derived here
    from the category (Groceries and Toiletries are essentials), because
    GET /search?essential_only=true has to filter on something. If the team
    wants a different rule, change ESSENTIAL_CATEGORIES below — not the SQL.

  * The dataset's `distance_km` and `rating` have nowhere to go: the schema has
    latitude/longitude on `stores` but no distance, and no rating column at
    all. Distance is therefore dropped here, which is exactly why the Search
    screen shows its radius filter as unavailable.
"""

import json
import pathlib
import sys

ESSENTIAL_CATEGORIES = {"Groceries", "Toiletries"}

HERE = pathlib.Path(__file__).resolve().parent


def sql_str(value):
    """Quote a value for SQL, or NULL."""
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    data = json.loads((HERE / "products.json").read_text())
    listings = data["products"]
    stores = data["stores"]

    out = sys.stdout.write
    out("-- Seed data for AI-Budgeting (generated by docs/seed/build_backend_seed.py)\n")
    out(f"-- Source: {data['meta']['dataset']} v{data['meta']['version']}, "
        f"{data['meta']['distinct_products']} products / {data['meta']['listing_count']} listings\n")
    out("-- Prices are indicative South African retail, Durban, September 2026.\n")
    out("-- Safe to re-run: it is wrapped in a transaction and keyed on external ids.\n\n")
    out("BEGIN;\n\n")

    # ---- retailer source ------------------------------------------------
    # source_type is CHECK (source_type IN ('online','physical','mixed','api')),
    # so 'mixed' is the only honest value for a hand-collected set covering both
    # high-street and online retailers. 'manual' is NOT allowed by the schema.
    out("-- One source row so the offers have a provenance, as the schema intends.\n")
    out("INSERT INTO retailer_sources (name, source_type, base_url, is_active)\n")
    out("SELECT 'Manual seed — Durban, Sept 2026', 'mixed', NULL, TRUE\n")
    out("WHERE NOT EXISTS (\n"
        "  SELECT 1 FROM retailer_sources WHERE name = 'Manual seed — Durban, Sept 2026'\n"
        ");\n\n")

    # ---- stores ---------------------------------------------------------
    out("-- stores: external_store_id keeps the team's slug so re-running is idempotent.\n")
    for s in stores:
        store_type = "online" if s["online_only"] else "physical"
        lat = "NULL" if s["online_only"] or s.get("lat") is None else s["lat"]
        lng = "NULL" if s["online_only"] or s.get("lng") is None else s["lng"]
        out(
            "INSERT INTO stores (name, store_type, address, latitude, longitude, external_store_id)\n"
            f"VALUES ({sql_str(s['store_name'])}, '{store_type}', {sql_str(s.get('suburb'))}, "
            f"{lat}, {lng}, {sql_str(s['store_id'])})\n"
            "ON CONFLICT DO NOTHING;\n"
        )
    out("\n")

    # ---- products (deduplicated across listings) ------------------------
    products = {}
    for row in listings:
        key = (row["name"], row["brand"], row["size"])
        products.setdefault(key, row)

    out(f"-- products: {len(products)} distinct items, deduplicated on (name, brand, size).\n")
    out("-- is_essential is derived from the category — see the script header.\n")
    for (name, brand, size), row in products.items():
        colour = row["colour"] if row["colour"] and row["colour"] != "n/a" else None
        essential = "TRUE" if row["category"] in ESSENTIAL_CATEGORIES else "FALSE"
        out(
            "INSERT INTO products (name, brand, category, colour, size, is_essential)\n"
            f"SELECT {sql_str(name)}, {sql_str(brand)}, {sql_str(row['category'])}, "
            f"{sql_str(colour)}, {sql_str(size)}, {essential}\n"
            "WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = "
            f"{sql_str(name)} AND COALESCE(brand,'') = COALESCE({sql_str(brand)},'') "
            f"AND COALESCE(size,'') = COALESCE({sql_str(size)},''));\n"
        )
    out("\n")

    # ---- offers ---------------------------------------------------------
    out(f"-- product_offers: {len(listings)} listings — the same item at several stores,\n")
    out("-- which is what makes the comparison screen worth anything.\n")
    out("-- total_cost is a GENERATED column, so it is never inserted here.\n")
    for row in listings:
        availability = "available" if row["in_stock"] else "out_of_stock"
        out(
            "INSERT INTO product_offers\n"
            "  (product_id, store_id, external_product_id, price, shipping_cost, currency, availability_status)\n"
            "SELECT p.id, s.id, "
            f"{sql_str(row['id'])}, {row['price']:.2f}, {row['shipping_fee']:.2f}, 'ZAR', '{availability}'\n"
            f"FROM products p, stores s\n"
            f"WHERE p.name = {sql_str(row['name'])}\n"
            f"  AND COALESCE(p.brand,'') = COALESCE({sql_str(row['brand'])},'')\n"
            f"  AND COALESCE(p.size,'')  = COALESCE({sql_str(row['size'])},'')\n"
            f"  AND s.external_store_id  = {sql_str(row['store_id'])}\n"
            "ON CONFLICT (store_id, external_product_id) DO UPDATE\n"
            "  SET price = EXCLUDED.price,\n"
            "      shipping_cost = EXCLUDED.shipping_cost,\n"
            "      availability_status = EXCLUDED.availability_status,\n"
            "      last_checked_at = NOW();\n"
        )

    out("\nCOMMIT;\n")


if __name__ == "__main__":
    main()
